arm64: configs: Enable bandwidth limiting options
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (ke
rnel FCM version = 7).
For kernel requirements at matrix level 7, Kernel config errors:
    Missing config CONFIG_NET_ACT_BPF
    Missing config CONFIG_NET_ACT_POLICE
    Missing config CONFIG_NET_CLS_MATCHALL
    Missing config CONFIG_NET_SCH_TBF

Change-Id: Ib7e08a6cffab5c48d24b55d2def0457ecbe1c768